### PR TITLE
#2 - Archive old websites

### LINKED ISSUE #3: Archive the old EclipseCon websites
Here is a list of all the websites that will need to be either archived or imported to this new repo. Now that ECF2018 has been achived and imported, we can use this as an example to import the other websites.

Drupal websites:
- [x] converge2017
- [x] europe2017
- [x] france2017
- [x] france2018

Archived websites:
- [x] 2004 
- [x] 2005   
- [x] 2006           
- [x] 2007     
- [x] 2008   
- [x] 2009        
- [x] 2010     
- [x] 2011    
- [x] 2012          
- [x] 2013             
- [x] locationcon     
- [x] europe2011       
- [x] europe2012 
- [x] europe2013  
- [x] europe2014   
- [x] europe2015 
- [x] europe2016    
- [ ] foss4g2015      
- [ ] foss4g2016   
- [ ] foss4g2018  
- [x] france2013       
- [x] france2014    
- [x] france2015  
- [x] france2016        
- [x] na2014    
- [x] na2015   
- [x] na2016         
- [x] na2017     
- [x] summiteurope2006      
- [x] summiteurope2007 
- [x] summiteurope2008
- [ ] summiteurope2009
- [ ] summiteurope2010

### PR DESCRIPTION
**Pull request by ericpoirier**
Fix #3

Signed-off-by: Eric Poirier <eric.poirier@eclipse-foundation.org>

### CODE REVIEW

**Review by chrisguindon — CHANGES_REQUESTED** [review]
I think the styles are missing for this event:
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2011/styles.css

**Comment by chrisguindon** [comment]
I created a link of links to allow everyone to review the sites before we merge this patch! I have to say, this is an impressive list of sites!

https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/converge2017
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2017
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2017
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2018
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2004
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2005
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2006
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2007
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2008
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2009
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2010
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2011
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2012
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2013
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/locationcon
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2011
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2012
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2013
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2014
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2015
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/europe2016
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/foss4g2015
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/foss4g2016
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/foss4g2018
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2013
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2014
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2015
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2016
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/na2014
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/na2015
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/na2016
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/na2017
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2006
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2007
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2008
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2009
https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/summiteurope2010

**Review by autumnfound — CHANGES_REQUESTED** [review]
It looks like none of NA, France (2013-2016), mainline (other than 2004 and 2005) sites are properly loading the styles.css (relative URL intentional?)

Additionally, Europe 2011 is missing styles.

Converge 2017 is also a broken link

**Comment by chrisguindon** [comment]
> It looks like none of NA, France (2013-2016), mainline (other than 2004 and 2005) sites are properly loading the styles.css (relative URL intentional?)
> 
> Additionally, Europe 2011 is missing styles.
> 
> Converge 2017 is also a broken link

I've ask Eric to fix these CSS files last week. Please see my previous comment.

**Comment by ericpoirier** [comment]
> I took a quick look and it seems that we are missing some styles in a few of our events.
> 
> For example: (This is not a complete list)
> https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2011/
> https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/na2015/
> https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2015/

I tested all the websites locally and I didn't find any issues with the styles not loading. I'm also seeing the pages without styles on Netlify but locally their all loading fine.

Not sure why Netlify doesn't loading the style.css tho?

While I was testing all the pages, I noticed some stuff that I fixed, like misaligned elements and missing logo in the footer.

**Comment by chrisguindon** [comment]
> > I took a quick look and it seems that we are missing some styles in a few of our events.
> > For example: (This is not a complete list)
> > https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/2011/
> > https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/na2015/
> > https://deploy-preview-4--eclipsefdn-eclipsecon-archive.netlify.app/france2015/
> 
> I tested all the websites locally and I didn't find any issues with the styles not loading. I'm also seeing the pages without styles on Netlify but locally their all loading fine.
> 
> Not sure why Netlify doesn't loading the style.css tho?
> 
> While I was testing all the pages, I noticed some stuff that I fixed, like misaligned elements and missing logo in the footer.


Your webpack file only has the following files:

mix.less('./less/france2018/styles.less', './content/france2018/styles.css');
mix.less('./less/france2017/styles.less', './content/france2017/styles.css');
mix.less('./less/europe2017/styles.less', './content/europe2017/styles.css');
mix.less('./less/europe2016/styles.less', './content/europe2016/styles.css');
mix.less('./less/europe2015/styles.less', './content/europe2015/styles.css');
mix.less('./less/europe2014/styles.less', './content/europe2014/styles.css');
mix.less('./less/europe2013/styles.less', './content/europe2013/styles.css');
mix.less('./less/europe2012/styles.less', './content/europe2012/styles.css');
~

**Pull request merged**
